apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-service
  labels:
    run: postgres-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: postgres-service
    spec:
      containers:
      - name: postgres-service
        image: postgres:9.5
        ports:
        - containerPort: 5432
          protocol: TCP