kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  clusterIP: None
  selector:
    run: postgres-service
  ports:
    - name: port1
      protocol: TCP
      port: 5432
      targetPort: 5432